export const TEST_CONFIG = {
  NODE_ENV: 'test' as const,
  PORT: 4300,
  API_PORT: 4300,
  DATABASE_URL: 'postgres://test:test@localhost/test_mcpforge',
  REDIS_URL: 'redis://localhost:6379',
  JWT_SECRET: 'test-secret-minimum-32-characters-long!!',
  ENCRYPTION_KEY: 'test-encrypt-minimum-32-chars-lo!!',
  AI_PROVIDER: 'mock' as const,
  AI_MODEL: 'mock',
  LOG_LEVEL: 'silent' as const,
  APP_BASE_URL: 'http://localhost:4301',
  API_BASE_URL: 'http://localhost:4300',
  OBJECT_STORAGE_BUCKET: 'test-bucket',
  FEATURE_AI_GENERATION: true,
  FEATURE_EXPORT_JSON: true,
  FEATURE_EXPORT_MARKDOWN: true,
  FEATURE_PUBLIC_EXAMPLES: true,
  FEATURE_APPROVAL_GATES: true,
}
