import type { TemplateSet } from '../types.js'

const server = `#!/usr/bin/env python3
"""{{connectorName}} MCP Server — generated by MCPForge on {{generatedAt}}"""
{{featuresComment}}
import asyncio
import json
from mcp.server.models import InitializationOptions
from mcp.server import NotificationOptions, Server
from mcp.types import TextContent, Tool
import mcp.server.stdio

server = Server("{{connectorName}}")

@server.list_tools()
async def handle_list_tools() -> list[Tool]:
    return [
        Tool(
            name="{{connectorName}}_list",
            description="List {{connectorName}} resources",
            inputSchema={
                "type": "object",
                "properties": {"query": {"type": "string", "description": "Optional search query"}},
            },
        ),
        Tool(
            name="{{connectorName}}_get",
            description="Get a {{connectorName}} resource by ID",
            inputSchema={
                "type": "object",
                "properties": {"id": {"type": "string", "description": "Resource ID"}},
                "required": ["id"],
            },
        ),
    ]

@server.call_tool()
async def handle_call_tool(name: str, arguments: dict) -> list[TextContent]:
    if name == "{{connectorName}}_list":
        results = {"connector": "{{connectorName}}", "query": arguments.get("query"), "results": []}
        return [TextContent(type="text", text=json.dumps(results))]
    if name == "{{connectorName}}_get":
        result = {"connector": "{{connectorName}}", "id": arguments.get("id"), "data": None}
        return [TextContent(type="text", text=json.dumps(result))]
    raise ValueError(f"Unknown tool: {name}")

async def main() -> None:
    async with mcp.server.stdio.stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="{{connectorName}}",
                server_version="1.0.0",
                capabilities=server.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={},
                ),
            ),
        )

if __name__ == "__main__":
    asyncio.run(main())
`

const readme = `# {{connectorName}} MCP Server

{{description}}

Generated by [MCPForge](https://mcpforge.dev) on {{generatedAt}}.

## Quick start

\`\`\`bash
pip install -r requirements.txt
python server.py
\`\`\`

## Tools

| Tool | Description |
|---|---|
| \`{{connectorName}}_list\` | List resources (optional \`query\` filter) |
| \`{{connectorName}}_get\` | Get a resource by \`id\` |
`

const tests = `import json
import pytest
import asyncio

# Import the handler directly so tests don't start the stdio server.
from server import handle_call_tool

@pytest.mark.asyncio
async def test_list_tool_returns_results_array():
    result = await handle_call_tool("{{connectorName}}_list", {"query": "test"})
    body = json.loads(result[0].text)
    assert isinstance(body["results"], list)
    assert body["connector"] == "{{connectorName}}"

@pytest.mark.asyncio
async def test_get_tool_returns_id_field():
    result = await handle_call_tool("{{connectorName}}_get", {"id": "abc"})
    body = json.loads(result[0].text)
    assert body["id"] == "abc"
    assert "data" in body

@pytest.mark.asyncio
async def test_unknown_tool_raises():
    with pytest.raises(ValueError, match="Unknown tool"):
        await handle_call_tool("nonexistent", {})
`

const dockerfile = `FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV PYTHONUNBUFFERED=1
CMD ["python", "server.py"]
`

// pyproject.toml used as the package manifest; requirements.txt for pip compatibility.
const packageJson = `[project]
name = "{{connectorNameLower}}-mcp-server"
version = "1.0.0"
description = "{{description}}"
requires-python = ">=3.11"
dependencies = ["mcp>=1.0.0"]

[project.optional-dependencies]
dev = ["pytest>=8.0.0", "pytest-asyncio>=0.23.0"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
`

// Python projects don't have a tsconfig — field is empty string.
const tsconfig = ``

const manifestTemplate = `{"name":"{{connectorName}}","version":"1.0.0","mcpVersion":"1.0","connectorType":"{{connectorType}}","outputLanguage":"{{outputLanguage}}","tools":["{{connectorName}}_list","{{connectorName}}_get"],"generatedBy":"MCPForge","generatedAt":"{{generatedAt}}"}`

export const pythonRestTemplate: TemplateSet = {
  server,
  readme,
  tests,
  dockerfile,
  manifestTemplate,
  packageJson,
  tsconfig,
}
