import type { TemplateSet } from '../types.js'

const server = `import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import { z } from 'zod'

{{featuresComment}}
const server = new McpServer({
  name: '{{connectorName}}',
  version: '1.0.0',
})

server.tool(
  '{{connectorName}}_list',
  { query: z.string().optional() },
  async ({ query }) => ({
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify({ connector: '{{connectorName}}', query, results: [] }),
      },
    ],
  }),
)

server.tool(
  '{{connectorName}}_get',
  { id: z.string() },
  async ({ id }) => ({
    content: [
      {
        type: 'text' as const,
        text: JSON.stringify({ connector: '{{connectorName}}', id, data: null }),
      },
    ],
  }),
)

const transport = new StdioServerTransport()
await server.connect(transport)
`

const readme = `# {{connectorName}} MCP Server

{{description}}

Generated by [MCPForge](https://mcpforge.dev) on {{generatedAt}}.

## Quick start

\`\`\`bash
npm install
npm run build
node dist/index.js
\`\`\`

## Tools

| Tool | Description |
|---|---|
| \`{{connectorName}}_list\` | List resources (optional \`query\` filter) |
| \`{{connectorName}}_get\` | Get a resource by \`id\` |

## Configuration

| Variable | Description | Required |
|---|---|---|
| \`MCP_SERVER_NAME\` | Override the server name | No |
`

const tests = `import { describe, it, expect } from 'vitest'

describe('{{connectorName}} MCP server', () => {
  it('loads without error', async () => {
    // TODO: import server and assert it initialises
    expect(true).toBe(true)
  })

  it('{{connectorName}}_list returns an array', async () => {
    // TODO: call tool handler and assert shape
    expect(true).toBe(true)
  })

  it('{{connectorName}}_get returns a data field', async () => {
    // TODO: call tool handler with id and assert shape
    expect(true).toBe(true)
  })
})
`

const dockerfile = `FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=builder /app/dist ./dist
ENV NODE_ENV=production
CMD ["node", "dist/index.js"]
`

const manifestTemplate = `{"name":"{{connectorName}}","version":"1.0.0","mcpVersion":"1.0","connectorType":"{{connectorType}}","outputLanguage":"{{outputLanguage}}","tools":["{{connectorName}}_list","{{connectorName}}_get"],"generatedBy":"MCPForge","generatedAt":"{{generatedAt}}"}`

export const typescriptRestTemplate: TemplateSet = {
  server,
  readme,
  tests,
  dockerfile,
  manifestTemplate,
}
